config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'data' => 'data#view'

  resource :users
  resources :sessions
  resource :project

end

app/models/project.rb
class Project < ActiveRecord::Base

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

    def password
    @password ||= BCrypt::Password.new(password_digest)
  end

  def password=(pass)
    @password = BCrypt::Password.create(pass)
    self.password_digest = @password
  end

  def self.authenticate(username, password)
    user = User.find_by_username(username)
    return user if user && (user.password == password)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if User.authenticate(params[:username], params[:password])
      @user = User.find_by_username(params[:username])
      session[:id] = @user.id
      redirect_to root_path
    else
      @error = "Please enter correct username/password"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @users = User.new
  end

  def create
    @user = User.new(user_params)
    if user_params[:username].present? && user_params[:password].present?
      @user.save
      session[:id] = @user.id
      p "========================="
      p session[:id]
      p "========================="

      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pickaxe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="signup">
    <h1>Sign Up</h1>
    <%= form_for @users do |f| %>
        <div>
          <%= f.label :username %>
          <%= f.text_field :username, class: "field" %>
        </div>
        <div>
          <%= f.label :password %>
          <%= f.password_field :password, class: "field" %>
        </div>
        <div>
          <%= f.label :email %>
          <%= f.text_field :email, class: "field" %>
        </div>
        <div>
          <%= f.submit "Sign Up", class: "button" %>
        </div>
    <% end %>
        <ul id="errors"></ul>
</div>

app/views/welcome/index.html.erb
<h1>PickAxe</h1>
<% if session %>
  <p><%= session[:id] %></p>
  <% end %>
  <div class="login">
    <%= form_tag('/sessions', method: "post") do %>
        <div>
          <%= label_tag "Username:" %>
          <%= text_field_tag :username, nil, class: "field" %>
        </div>
        <div>
          <%= label_tag "Password:" %>
          <%= password_field_tag :password, nil, class: "field" %>
        </div>
        <div>
          <%= submit_tag "Sign In", class: "button signin_button" %>
        </div>
    <% end %>
  </div>
    <%= link_to "Sign Up", new_users_path %>
    <%= link_to "Sign Out", 'sessions/session[:id]', method: :delete %>